/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void portList_click(GDropList source, GEvent event) { //_CODE_:portList:640344:
  //println("portList - GDropList >> GEvent." + event + " @ " + millis());
  selectedPort = portList.getSelectedText();
  startSerial();
} //_CODE_:portList:640344:

public void record_click(GButton source, GEvent event) { //_CODE_:record:731936:
  //println("record - GButton >> GEvent." + event + " @ " + millis());
  ////////////////////////////////////////////////////////////////////////////////
  //
  //    Enable the buttons and calls the serial port function
  //    Comselect is made true to call the serial function
  //  
  ///////////////////////////////////////////////////////////////////////////////
  try
  {
    jFileChooser = new JFileChooser();
    jFileChooser.setSelectedFile(new File("log.csv"));
    jFileChooser.showSaveDialog(null);
    String filePath = jFileChooser.getSelectedFile()+"";

    if ((filePath.equals("log.txt"))||(filePath.equals("null")))
    {
    } else
    {    
 //     done.setVisible(true);
      record.setVisible(false);
      close.setEnabled(false);
      close.setLocalColorScheme(GCScheme.CYAN_SCHEME);
      logging = true;
      date = new Date();
      output = new FileWriter(jFileChooser.getSelectedFile(), true);
      bufferedWriter = new BufferedWriter(output);
      bufferedWriter.write(date.toString()+"");
      bufferedWriter.newLine();
      bufferedWriter.write("TimeStramp,ECG,SpO2,Respiration");
      bufferedWriter.newLine();
    }
  }
  catch(Exception e)
  {
    println("File Not Found");
  }
} //_CODE_:record:731936:

public void close_click(GButton source, GEvent event) { //_CODE_:close:222350:
  //println("close - GButton >> GEvent." + event + " @ " + millis());
  int dialogResult = JOptionPane.showConfirmDialog (null, "Would You Like to Close The Application?");
  if (dialogResult == JOptionPane.YES_OPTION) {
    try
    {
      //Runtime runtime = Runtime.getRuntime();
      //Process proc = runtime.exec("sudo shutdown -h now");
      System.exit(0);
    }
    catch(Exception e)
    {
      exit();
    }
  } else
  {
  }
} //_CODE_:close:222350:

public void imgButton1_click1(GImageButton source, GEvent event) { //_CODE_:imgButton1:665258:
  println("imgButton1 - GImageButton >> GEvent." + event + " @ " + millis());
} //_CODE_:imgButton1:665258:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.RED_SCHEME);
  G4P.setCursor(ARROW);
  surface.setTitle("Healthy Pi");
  portList = new GDropList(this, 5, 7, 200, 385, 10);
  portList.setItems(loadStrings("list_640344"), 0);
  portList.setLocalColorScheme(GCScheme.RED_SCHEME);
  portList.addEventHandler(this, "portList_click");
  record = new GButton(this, 319, 7, 100, 40);
  record.setText("RECORD");
  record.setTextBold();
  record.setLocalColorScheme(GCScheme.RED_SCHEME);
  record.addEventHandler(this, "record_click");
  close = new GButton(this, 434, 7, 100, 40);
  close.setText("CLOSE");
  close.setTextBold();
  close.setLocalColorScheme(GCScheme.RED_SCHEME);
  close.addEventHandler(this, "close_click");
 imgButton1 = new GImageButton(this, (width-100), 5, 70, 70, new String[] { "heart.png", "heart.png", "heart.png" } );
  imgButton1.addEventHandler(this, "imgButton1_click1");
  
   imgButton2 = new GImageButton(this, (width-290), 165, 70, 70, new String[] { "greenheart.png", "greenheart.png", "greenheart.png" } );
  imgButton2.addEventHandler(this, "imgButton1_click1");
  
     imgButton3 = new GImageButton(this, (width-295), 330, 70, 70, new String[] { "yellowspo.png", "yellowspo.png", "yellowspo.png" } );
  imgButton3.addEventHandler(this, "imgButton1_click1");
  
  imgButton4 = new GImageButton(this, (width-295), 520, 70, 70, new String[] { "blueres.png", "blueres.png", "blueres.png" } );
  imgButton4.addEventHandler(this, "imgButton1_click1");
  
    imgButton5 = new GImageButton(this, (width-295), 680, 70, 70, new String[] { "redtemp.png", "redtemp.png", "redtemp.png" } );
  imgButton5.addEventHandler(this, "imgButton1_click1");
  
    imgButton6 = new GImageButton(this, (width-520), -4, 40, 40, new String[] { "ecgrmbbc.png", "ecgrmbbc.png", "ecgrmbbc.png" } );
  imgButton6.addEventHandler(this, "imgButton1_click1");
  
      imgButton7 = new GImageButton(this, (width-220), -4, 70, 70, new String[] { "yemen.jpg", "yemen.jpg", "yemen.jpg" } );
  imgButton7.addEventHandler(this, "imgButton1_click1");
  
  
  bpm1 = new GLabel(this, (width-250), 165, 250, 80);
  bpm1.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  bpm1.setText("");
  bpm1.setTextBold();
  bpm1.setOpaque(false);
    bpm = new GLabel(this, (width-250), 165, 250, 80);
  bpm.setTextAlign(GAlign.RIGHT, GAlign.MIDDLE);
  bpm.setText("bpm");
  bpm.setTextBold();
  bpm.setOpaque(false);
    HR = new GLabel(this, (width-290), 80, 250, 80);
  HR.setTextAlign(GAlign.LEFT, GAlign.MIDDLE);
  HR.setText("HR");
  HR.setTextBold();
  HR.setOpaque(false);
  
    titel = new GLabel(this, (width-700), -10, 250, 80);
  titel.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  titel.setText("RMSPPS");
 titel.setTextBold();
  titel.setOpaque(false);
    titel2 = new GLabel(this, (width-700), 10, 250, 80);
  titel2.setTextAlign(GAlign.RIGHT, GAlign.MIDDLE);
  titel2.setText("UST biomedical engering department");
 titel2.setTextBold();
  titel2.setOpaque(false);
  
  SP02 = new GLabel(this, (width-250), 330, 250, 80);
  SP02.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  SP02.setText("");
  SP02.setTextBold();
  SP02.setOpaque(false);
  
    oxgen_satp = new GLabel(this, (width-250), 330, 250, 80);
  oxgen_satp.setTextAlign(GAlign.RIGHT, GAlign.MIDDLE);
  oxgen_satp.setText("%");
  oxgen_satp.setTextBold();
  oxgen_satp.setOpaque(false);
  
  oxgen_sat = new GLabel(this, (width-290),240, 250, 80);
   oxgen_sat.setTextAlign(GAlign.LEFT, GAlign.MIDDLE);
   oxgen_sat.setText("SPO2");
   oxgen_sat.setTextBold();
   oxgen_sat.setOpaque(false);
  //BP = new GLabel(this, (width-250), (height-400), 225, 100);
  //BP.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
 //BP.setText("BP: ---/---");
  //BP.setTextBold();
  //BP.setOpaque(false);
  
  Temp = new GLabel(this, (width-250), 680, 250, 58);
  Temp.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  Temp.setText("");
  Temp.setTextBold();
  Temp.setOpaque(false);
    tempraturep = new GLabel(this, (width-250), 680, 250, 58);
  tempraturep.setTextAlign(GAlign.RIGHT, GAlign.MIDDLE);
  tempraturep.setText("C");
  tempraturep.setTextBold();
  tempraturep.setOpaque(false);
    temprature = new GLabel(this, (width-290), 600, 250, 58);
  temprature.setTextAlign(GAlign.LEFT, GAlign.MIDDLE);
  temprature.setText("TEMP");
  temprature.setTextBold();
  temprature.setOpaque(false);
  
  rpm = new GLabel(this, (width-250), 530, 250, 62);
  rpm.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  rpm.setText("");
  rpm.setTextBold();
  rpm.setOpaque(false);
    rpm2= new GLabel(this, (width-250), 540, 250, 62);
  rpm2.setTextAlign(GAlign.RIGHT, GAlign.MIDDLE);
  rpm2.setText("Bpm");
  rpm2.setTextBold();
  rpm2.setOpaque(false);
  RES = new GLabel(this, (width-290), 420, 250, 62);
  RES.setTextAlign(GAlign.LEFT, GAlign.MIDDLE);
  RES.setText("RR");
  RES.setTextBold();
  RES.setOpaque(false);
}

// Variable declarations 
// autogenerated do not edit
GDropList portList; 
GButton record; 
GButton close; 
GImageButton imgButton1; 
GImageButton imgButton2;
GImageButton imgButton3;
GImageButton imgButton4; 
GImageButton imgButton5; 
GImageButton imgButton6; 
GImageButton imgButton7; 
GLabel bpm1; 
GLabel oxgen_sat;
GLabel oxgen_satp;
GLabel HR; 
GLabel SP02; 
GLabel BP; 
GLabel bpm;
GLabel RES; 
GLabel label1; 
GLabel label4; 
GLabel Temp; 
GLabel titel;
GLabel titel2;
GLabel label5; 
GLabel label7; 
GLabel label8; 
GLabel rpm; 
GLabel rpm2;
GLabel label11; 
GLabel temprature; 
GLabel tempraturep; 